const pongDescription = "The goal of this project was to create a game along with its game controller.  To start my Pong game, I felt that creating the game itself would be more difficult than creating the controller for it.  I used a variety of classes for pong: the A.I., the paddle, and the ball.  The game itself used pygame, but I only used the draw function with the main window.  The physics for the bouncing took into account the x and y position of the ball, where the ball had a constant velocity by using the draw function.  After completing the game, I moved onto the controller, which used a bluetooth module using AT commands from the Arduino. I used bluetoothserial along with a joystick to communicate with pong."

const d3Description = "This project utilized d3 and a data set to create a bar graph of GDP for the United States from 1947 to 2015.  The data first needed to be extracted from the JSON file of the U.S. GDP.  Then, using d3's libraries, the data was rendered onto a bar graph.  If hovered over a particular bar, the year and the total annual GDP of that year will be shown."

const lifeDescription = "The game of life is a game that exhibits a pattern each generation, changing each square with life or death.  Following the game's rules, I created a game of life clone using react and electron as the desktop app. The trick to figuring out the game of life was the life condition for each individual square.  I used a 1D array and had a fixed column and row number.  Knowing these two facts, I just had to add or subtract the row size from the current position to acquire information on every cell surrounding the current square."

const ecocarDescription ="My job on the Shell Eco-marathon team was to create a methane detector to act as a shut off switch for the car.   The methane detector was a needed safety feature to protect against unforeseen natural gas leaks in the car.  I programmed an Arduino Nano to act as a shut off switch for the car.  The Arduino was connected to a buck converter that supplied around 5V. When the Arduino sensed methane a shut off current would reach a Darlington NPN transistor and shut off the car relay that was supplying power. The competition was a great experience and I encourage you to look at more of Shell Eco-marathon if you are interested about this event!";

const pomodoroDescription = "The Pomodoro clock is known as a tomato clock.  The clock is set with a resting time and a working time.  To program this project, I used react and redux-react to keep track of the time.  This project helped me to learn about how redux functions and the benefits of having a single storage for state by using action creators and reducers. "

const matrixDescription = "This was one of the projects on the Arduino I enjoyed creating the most.  I had done the assembly of the light responsive matrix in steps and the first step was setting up the LED matrix to receive power to turn on.  To do this, I needed to use a lot of pins or, in my case, I used a few HC595 shift registers to control the state of the LED matrix.  Then, on the Arduino, I ran C code to respond to shift registers and the microphone input.  To process the microphone input, I attempted to use FFT, but the Arduino I had was too slow to sample well enough for the incoming signal.  The best result was with 7 bit accuracy which meant the Arduino could only tell the difference in frequency for every 340 Hz steps."

const weatherDescription = "This project was for getting my feet wet reading JSON data.  I had never read JSON data from an API and applied it to my projects until this weather app.  This app uses geolocation to tell the weather in your area.  I used jQuery to process the incoming JSON data and transfer it to my app."

const tributePage = "This was my absolutely first project using HTML and CSS.  I thought that the best way for my first project to go was to combine it with one of the things I like the most, which in this case was cooking.  The tribute page talks about Escoffier, a famous French chef who revolutionized not only French cooking but also the art of cooking itself."

const iotLed = "When I was tinkering with the Raspberry Pi, I thought it would be a cool idea to try and combine my electronics knowledge with my web design knowledge.  The result was my IoT led to turn on.  It was a cool \"Hello World\" experience with the combination of hardware and software.  For the project, I used Node.js on the Raspberry Pi, along with socket.io to communicate with client and server."

const mbedDescription = "This project occurred in one of my electrical engineering classes. I was in a group with 2 other teammates and there were about 5 teams in total for the project.  Each team had a different task that needed to interact with another team without knowing the entire specifics of the inputs and outputs.  Our team's job was to create an interface to work with the other teams' part.  To do this, we used an MBED device which uses C/C++ code for communication.  We used serial buses to communicate with other teams using putty, a program used to send and receive data through serial communication."

const cadenceDescription = "While in one of my classes, Cadence was used to simulate circuit behaviors that were seen.  I designed many circuits including differential operational amplifiers, telescopic amplifiers, folded cascode amplifiers, and many other configurations.  The particular circuit built in the picture is a folded cascode amplifier with feedback in order to prevent inaccuracies in amplification.  The circuit was folded to reach the wanted voltage swing for the circuit and the 4 PMOS and NMOS transistors were used to amplify the circuit to a larger degree without going to a second stage."

const waferDescription = "One of the most hands on labs that I was able to do at Penn State was in an electronics materials class.  This class' projects presented the means to create a transistor in the nanoscale range.  As seen in the picture, students had to enter a clean room in order to prevent contaminants from harming the transistors' electrical properties.  We followed procedures such as lithography, spinning photoresist, and sputtering to create a transistor."

const descriptions = [pongDescription, d3Description, lifeDescription, ecocarDescription, pomodoroDescription, matrixDescription, weatherDescription, tributePage, iotLed, mbedDescription, cadenceDescription, waferDescription];
export default descriptions
